### ISSUE TITLE
Error: Failed to start database, when attempting to start local database

### ISSUE THREAD

**Issue by danwilliams** [StarlaneStudios/Surrealist#108]
**Describe the bug**
When trying to start a local database (using the play button top-right of the desktop app) it does not work, and pops up the following message:

> **Failed to start database**
> SurrealDB did not start correctly, check the console for more information

![image](https://github.com/StarlaneStudios/Surrealist/assets/365912/046f949d-8bd8-4bf9-91dd-2ce9b9d7135c)

Moreover, what "console" is it referring to? There is no console available that can be seen.

This is on a brand-new installation of Surrealist.

**To Reproduce**
1. Download the latest 1.9.1 release for Windows, and install it
2. Run it
3. Click the "Start local database" button
4. Observe the error message

**Expected behavior**
Based on the documentation, it should start a local database server to use. It would also be helpful if the console referred to was available.

**Environment:**
 - Operating System: Windows 11 
 - Surrealist Version: 1.9.1
 - SurrealDB Version: ???

**Comment by macjuul** [comment]
You can toggle the console using this button

![image](https://github.com/StarlaneStudios/Surrealist/assets/7606171/5228af3d-6934-44de-8f14-5e14aed18bcb)

It should provide clues about the cause of this issue

**Comment by danwilliams** [comment]
@macjuul thanks for the reply. I do not have such a button:

![image](https://github.com/StarlaneStudios/Surrealist/assets/365912/b098db84-08d3-4068-b6d3-b4b9021331c7)
![image](https://github.com/StarlaneStudios/Surrealist/assets/365912/2c8e2d9d-3fe7-428b-92c0-e3bea09fc6c9)

**Comment by macjuul** [comment]
It's only visible when you create a session (it's not related to the session though). I understand it may be unclear so I plan on revising and changing the database launch UI in the near future.

**Comment by danwilliams** [comment]
@macjuul I see, that's why I don't have that button then. But why am I getting the error message? All I've done is install Surrealist and click the "Start local database" button to start a local session, which I understood from the documentation should spin up a local SurrealDB instance to use? My understanding was that this is an alternative to using the "Create session" button to connect to an existing instance?

**Comment by macjuul** [comment]
You can indeed launch a local SurrealDB instance by pressing the start button, however you still need a session in order to connect to it (endpoint would be `localhost:8000` for example)

Separately, due to UI constraints at the time I made this the "Reveal console" button is only visible when you have a session open. It doesn't actually have anything to do with that session, so I intend on changing it soon to make it more clear.

Coming back to your first post, it looks like something is going wrong when starting the database (this could have a variety of reasons). By revealing the console panel we can get some additional hints as to why it may be failing

**Comment by danwilliams** [comment]
@macjuul understood... I think.

My impression from the docs was that pressing the "Start local database" button would spin up a local instance for me, and connect to it. I see that this was partly wrong.

However, I have no idea what to enter into the new session config - I don't know what the defaults would be for the local session. It won't accept endpoint alone.

Am I better off just setting up a "proper" SurrealDB installation and connecting to it in a more normal manner? I had tried this because it seemed like a quick and convenient way of poking at SurrealDB.

**Comment by danwilliams** [comment]
I tried speculatively...

> You can start a local database directly from the application by pressing the start button in the top right. Doing so will start up a SurrealDB instance using the credentials and port entered for the current tab.

It's not quite clear when you first use the app what this means, but combining with your feedback I conclude I am meant to create a session and then can create a new local database with the "Start" button - but trying this doesn't work:

![image](https://github.com/StarlaneStudios/Surrealist/assets/365912/a80e9fc7-dd7b-40b9-998f-16784fff982a)

All the values are required, so I've given it test values and the session does get created, but then I just get the same error when clicking "Start":

![image](https://github.com/StarlaneStudios/Surrealist/assets/365912/6104f556-5a11-404e-bf0e-9aaf08604a44)

However, I can at least now see the console. And the error there suggests that I should have SurrealDB installed already, somewhere in my path? If so, that's not the impression I had got from reading the docs - they made it sound (to me, at least) like it was built-in. I've re-read them, and it doesn't mention that I need to have installed SurrealDB, or how I would do that locally to be picked up.

I think I am best off going the traditional route and spinning up a Docker container for it, and then connecting in the usual fashion 🙂 It just seemed very attractive to be able to download Surrealist and use a local database without that faff if the intention is just to try things out. Perhaps this can be made clearer in the docs...? Or maybe I am just stupid 😅

**Comment by macjuul** [comment]
Surrealist doesn't bundle a database executable, you still need to download SurrealDB yourself and either place it in your PATH or alternatively configure the path to the executable in the settings. Surrealist simply removes the need to manually start a database using the CLI which can be cumbersome.

I'm sorry if the documentation isn't clear enough, I'll see if I can reword and update it once I have time for that.

Additionally, I do have intentions to bundle an embedded database in the near future similar to what you are looking for, however due to how SurrealDB works it wouldn't expose an API for other applications to connect to, so it will be primarily limited for testing and experimenting.

**Comment by danwilliams** [comment]
@macjuul I see - that you for explaining that, that makes sense. What you have described as your future goals sound exactly like what I was expecting/wanting, possibly encouraged by the fact that SurrealDB makes itself available as an embeddable library as well as a standalone application. With that small fact in mind, I therefore thought it quite natural that you would have embedded it and make it available to play with. I think I've just jumped the gun on that! 🙂
