### ISSUE TITLE
Please bring back the query duration

### ISSUE THREAD

**Issue by TudorAndrei-Pythia** [StarlaneStudios/Surrealist#113]
**Describe your feature request**
Previously the query duration was shown in the Result view. It was a great indicator to see if I messed up a query that didn't give me an error. Currently if I rerun a query I can't tell if something changed.

**Are you willing to contribute this feature?**
No

**Comment by macjuul** [comment]
Since Surrealist now uses the official SurrealDB Rust crate for making connections this is currently not possible as unlike the WebSocket protocol no time value is made available.

If SurrealDB would implement this functionality I would absolutely add the time value back as I too found it very useful. I'll keep looking into this.

**Comment by macjuul** [comment]
Quick update, I've personally added support for retrieving query times into the SurrealDB Rust SDK and will be using it in the next Surrealist release.
