### ISSUE TITLE
1.DEFINE FUNCTION, 2.RETURN fn::function_name, 3.REMOVE FUNCTION - not returns correct result like browser

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#115]
**Describe the bug**
1.DEFINE FUNCTION, 2.RETURN fn::function_name, 3.REMOVE FUNCTION - not returns correct result like browser

**To Reproduce**
```sql
DEFINE FUNCTION fn::greet($name: string) {
	RETURN "Hello, " + $name + "!";
};

RETURN fn::greet("Tobie");

REMOVE FUNCTION fn::greet;
```
1. DEFINE FUNCTION
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/15a6280b-403a-4aa7-b846-77299d82398d)

2. RETURN fn::greet, In this case, the function returns a string, not an array,
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/3b444925-2e5e-4b02-ba28-ef6d872b58a3)

3. REMOVE FUNCTION 
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/0b0c17bd-077f-4751-bade-7a20a498ad78)

**Expected behavior**
all result must be like browser surrealist

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 10
 - Surrealist Version [e.g. 1.2.0]: 1.9.2
 - SurrealDB Version [execute "surreal version"]: 1.0.0

**Comment by macjuul** [comment]
This is the case because the desktop app uses the Rust SDK for executing queries while the browser uses a custom web socket implementation (which has limitations on its own).

I have recently migrated this logic to WebAssembly for use in both desktop and browser, meaning the desktop logic will become the way forward for both platforms. As you have noticed however there are some cases where response types are returned incorrectly, which I'll look into and try to resolve

**Comment by macjuul** [comment]
After further research it looks like this is a limitation in SurrealDB. The Rust SDK internally represents each response as a `Vec<Value>` meaning every response is always converted to an array the moment I `.take()` the result.

I found [this issue](https://github.com/surrealdb/surrealdb/issues/2714) which may be related, however I can see you've already found it yourself as well. I'll keep track of this and will implement a fix as soon as one is available.

**Comment by macjuul** [comment]
This issue should finally be fixed in the next version of Surrealist now a fix has been provided in SurrealDB.
