### ISSUE TITLE
Add grammar color for UNSET, FLEXIBLE, option, <, >, record

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#120]
**Describe the bug**
Add grammar color for UNSET, FLEXIBLE, option, <, >, record

**To Reproduce**
```sql
UPDATE test UNSET child WHERE age > 10;
SELECT (SELECT inventory from inv_txns[WHERE inventory = inventory:apple]) as inv_txns, voucher_no from sale;
DEFINE FIELD ac_adjs.shipping_charge ON sale_quotation TYPE option<object | null>  VALUE IF $value THEN fn::round($value, 2) ELSE NONE END;
DEFINE FIELD ac_adjs.shipping_tax ON sale_quotation TYPE option<record<gst_tax> | null>;
DEFINE FIELD ac_adjs.shipping_tax ON sale_quotation FLEXIBLE TYPE object;
```
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/a650a5fa-65cf-46b7-94cf-17c7849e406a)

**Expected behavior**
add color for keywords

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]:  11
 - Surrealist Version [e.g. 1.2.0]: 1.0.0
 - SurrealDB Version [execute "surreal version"]:  1.0.0

**Comment by macjuul** [comment]
All these issues will be fixed in the next release :)

For context, we currently use the official [surrealql-grammar](https://github.com/surrealdb/surrealql-grammar) under the hood so issues regarding missing keywords and incorrect highlighting are best reported there. I've worked together with Micha to have all these issues resolved in both the official grammar and in Surrealist.

Side note, thank you for all the issues you've opened recently. They are useful and much appreciated!
