### ISSUE TITLE
Connection Closed Unexpected connection close (1006) when trying to open table with 100k records

### ISSUE THREAD

**Issue by AskoldMakaruk** [StarlaneStudios/Surrealist#17]
**Describe the bug**
I have a table with aproximatly 100k events. When I'm trying to navigate to the table view in explorer I get Connection Closed
Unexpected connection close (1006). Changings Results per page didn't help.

**To Reproduce**
1. Select Explorer
2. Click on some large table
3. Get Connection Closed Unexpected connection close (1006)

**Expected behavior**
Table records are shown.

**Environment (you can view the current version under Settings):**
 - OS: Windows
 - Version 1.5.2

**Comment by macjuul** [comment]
I'm aware of this issue and have reproduced it. Unfortunately this appears to be caused by SurrealDB terminating the connection abruptly when querying the database to retrieve the total amount of rows (required to render pagination in the explorer view).

I plan on opening an issue upstream with SurrealDB since I don't believe there is any good way of fixing this as there are known problems and performance issues when retrieving row count.

My apologies for the inconvenience

**Comment by macjuul** [comment]
@AskoldMakaruk could you please run `surreal version` and give me the output?

**Comment by AskoldMakaruk** [comment]
> @AskoldMakaruk could you please run `surreal version` and give me the output?

1.0.0-beta.8+20221227.fee14d8 for unknown on unknown
