### ISSUE TITLE
Query: execute only selected text

### ISSUE THREAD

**Issue by AskoldMakaruk** [StarlaneStudios/Surrealist#18]
**Describe your feature request**
Query window should execute only selected code, to make it easier to work with many different statements in one window.
Maybe you could also add a little run icon for statments in the gutter?  
**Are you willing to contribute this feature?**
I hope I can help but I don't know Go and TS is not my strongest lang.

**Comment by clarkmcc** [comment]
Is it possible to make executing the selected query the default behavior, rather than having to select, then right-click, then choose "Execute Selected"? This is the default behavior of almost every other database IDE that I've personally used. Happy to open a new issue if this is a change that this project would consider.
