### ISSUE TITLE
Darwin releases seems to be swapped (architecture–wise)

### ISSUE THREAD

**Issue by ri-nat** [StarlaneStudios/Surrealist#24]
**Describe the bug**
I have downloaded Surrealist `arm64` version, since I'm using Mac with M1 chip, but the application is not starting up, displaying the `“Surrealist” is damaged and can’t be opened. You should move it to the Bin.` error from the operating system. The interesting part is that the version labeled `amd64` is working perfectly.

<img width="64" alt="Screenshot 2023-02-18 at 3 09 31 AM" src="https://user-images.githubusercontent.com/6157581/219823469-2efc8de0-d310-425e-a2a3-c13efc475d98.png"> 
<img width="64" alt="Screenshot 2023-02-18 at 3 04 39 PM" src="https://user-images.githubusercontent.com/6157581/219867447-44f95dc2-8625-4665-a416-fc8012e6feef.png">

**To Reproduce**
1. Download release labeled `arm64` to Mac computer with M-family chip: https://github.com/StarlaneStudios/Surrealist/releases/download/v1.5.2/surrealist-v1.5.2-darwin-arm64.tgz
2. Unpack, run the program, observe the error message
3. Repeat (1) for `amd64` version: https://github.com/StarlaneStudios/Surrealist/releases/download/v1.5.2/surrealist-v1.5.2-darwin-amd64.tgz
4. Unpack, run the program - it works well

**Environment (you can view the current version under Settings):**
 - OS: MacOS 13.0.1
 - Version 1.5.2

**Comment by macjuul** [comment]
This is a known issue, in fact the binaries should be of the correct architecture. The issue is that MacOS quarantines the ARM binaries and incorrectly reports them as broken. You can manually remove this quarantine attribute to fix the issue (see readme for more information).

The AMD binaries appear to work fine on both AMD and ARM without getting quarantined (no clue why) so it's recommended to use these for now.

**Comment by ri-nat** [comment]
oh, thats why. Thank you for the explanation!
