### ISSUE TITLE
Failed to connect to insecure websocket

### ISSUE THREAD

**Issue by bibaswan-bhawal** [StarlaneStudios/Surrealist#29]
**Describe the bug**
When trying to connect to an external DB over http instead of the https the client fails and throws:

![2023-03-04 20_34_00-Surrealist](https://user-images.githubusercontent.com/67685395/222942319-dad44181-8cd0-43f7-8b46-b5dfca815c03.png)

This behaviour appeares to be  windows specific. Works fine on MacOS

**To Reproduce**
- Install surrealist using msi from github
- attempt to connect to external db over http

**Expected behavior**
Surrealist connects to db.

**Environment (you can view the current version under Settings):**
 - OS: Windows
 - Version 1.6.1

**Comment by macjuul** [comment]
As far as I'm aware there is no easy fix for this issue as it's mandated by the browser, and since Surrealist uses a web view it is constrained to these rules. The only solution at this moment in time is to wrap your database endpoint with a SSL certificate.

A long term solution would be to move connection logic to the Rust backend, however we will be required to keep the current implementation for the hosted web app (https://surrealist.app)

I'll try to work on this in the near future

**Comment by bibaswan-bhawal** [comment]
ya I realised that and added an ssl certificate to my endpoint

**Comment by kameko** [comment]
For those using Windows 11 and don't know how to run a localhost SurrealDB over HTTPS and don't feel like going down the rabbit hole of extremely long, complex and incorrect answers on StackOverflow, here's how you accomplish it:

Get a release from https://github.com/FiloSottile/mkcert
Run `.\mkcert -install localhost 127.0.0.1 ::1 0.0.0.0` to get the cert and key files.
Pass `--web-crt path/to/localhost+3.pem --web-key path/to/localhost+3-key.pem` to `surreal start`
Connect with `https://localhost:[your port]`, *not* `0.0.0.0` like what the SurrealDB example uses for starting the server.

And that's an afternoon I'll never get back.

**Comment by macjuul** [comment]
For those running into this issue, this has now been fixed on the `nightly` branch with an overhaul to how Surrealist connects to SurrealDB. I intend to release this once beta 10 is available, however you may build from source to try it out already
